#role user
sudo: required
#OS yang digunakan
dist: trusty
#bhs yg digunakan
language: php
#versi bhasa yang digunakan
php: 
    - 7.1
#branch
branches:
    only:
       - master
       - devolop
#sebelum instal
before_install:
    - cp .env.travis .env
    - composer install --no-interaction
    - php artisan key:generate


#proses instal
install:
    - sudo mv phpunit-7.phar phpunit

# befre script running
before_script:
    - ./phpunit --version

#script main ekcecution
script:
    - - ./vendor/bin/phpunit
#after success
after_success: